# Generated by Django 5.1.6 on 2025-03-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='month_year',
        ),
    ]
