# Generated by Django 5.0.2 on 2025-03-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_options_remove_todo_priority_todo_shared'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['due_date', '-created_at']},
        ),
    ]
